stages:
- render
- export

variables:
  FILENAME: slides.adoc
  HTML_FILE: slides.html
  PDF_FILE: slides.pdf

html:
  stage: render
  image: docker.io/library/node:lts-alpine
  script:
  - npm install
  - npm run build
  # We need artifacts in the decktape job
  artifacts:
    name: "${CI_PROJECT_NAME}_${CI_COMMIT_REF_SLUG}_${CI_JOB_NAME}"
    paths:
    - ${HTML_FILE}
    - assets
    - theme
    - node_modules/asciinema-player
    - node_modules/reveal.js
    - node_modules/typeface-ubuntu
    - node_modules/typeface-ubuntu-mono

pdf:
  stage: export
  image:
    name: docker.io/astefanutti/decktape:2.9.2
    entrypoint:
    - /bin/sh
    - -c
  script:
  - node /decktape/decktape.js
    --chrome-path chromium-browser
    --chrome-arg=-no-sandbox
    --size '2560x1440'
    --chrome-arg=--allow-file-access-from-files $(pwd)/${HTML_FILE}
    ${PDF_FILE}
  artifacts:
    name: "${CI_PROJECT_NAME}_${CI_COMMIT_REF_SLUG}_${CI_JOB_NAME}"
    paths:
    - ${PDF_FILE}
