stages:
- render
- export

variables:
  FILENAME: slides.adoc
  HTML_FILE: slides.html
  PDF_FILE: slides.pdf
  ASSETS: assets

html:
  stage: render
  image:
    name: docker.io/vshn/asciidoctor-slides:1.0
    entrypoint:
    - /bin/sh
    - -c
  script:
  - mkdir /build
  - cp -R ${ASSETS} /build/${ASSETS}
  - cp ${FILENAME} /build/${FILENAME}
  - cd /presentation
  - generate-vshn-slides ${FILENAME}
  - cp /build/${HTML_FILE} ${CI_PROJECT_DIR}
  - cp -R /presentation/theme ${CI_PROJECT_DIR}/theme
  - cp -R /presentation/node_modules ${CI_PROJECT_DIR}/node_modules
  # We need artifacts in the decktape job
  artifacts:
    name: "${CI_PROJECT_NAME}_${CI_COMMIT_REF_SLUG}_${CI_JOB_NAME}"
    paths:
    - ${HTML_FILE}
    - assets
    - theme
    - node_modules/asciinema-player
    - node_modules/reveal.js
    - node_modules/typeface-ubuntu
    - node_modules/typeface-ubuntu-mono

pdf:
  stage: export
  image:
    name: docker.io/astefanutti/decktape:2.9.2
    entrypoint:
    - /bin/sh
    - -c
  script:
  - node /decktape/decktape.js
    --chrome-path chromium-browser
    --chrome-arg=-no-sandbox
    --size '2560x1440'
    --chrome-arg=--allow-file-access-from-files $(pwd)/${HTML_FILE}
    ${PDF_FILE}
  artifacts:
    name: "${CI_PROJECT_NAME}_${CI_COMMIT_REF_SLUG}_${CI_JOB_NAME}"
    paths:
    - ${PDF_FILE}
