stages:
- render
- export

render:
  stage: render
  image: docker.io/library/node:lts-alpine
  variables:
    FILENAME: slides.adoc
  script:
  - npm install
  - npm run build
  artifacts:
    name: "${CI_COMMIT_REF_SLUG}-html-${CI_JOB_NAME}"
    paths:
    - slides.html
    - assets
    - theme
    - node_modules/asciinema-player
    - node_modules/reveal.js
    - node_modules/typeface-ubuntu
    - node_modules/typeface-ubuntu-mono

build:
  stage: export
  image:
    name: docker.io/astefanutti/decktape:2.9.2
    entrypoint:
    - /bin/sh
    - -c
  script:
  - ls -lah
  - node /decktape/decktape.js --chrome-path chromium-browser --chrome-arg=-no-sandbox --size '2560x1440' --chrome-arg=--allow-file-access-from-files $(pwd)/slides.html slides.pdf
  artifacts:
    name: "${CI_COMMIT_REF_SLUG}-pdf-${CI_JOB_NAME}"
    paths:
    - slides.pdf
