= Reveal.js Presentation Template

Fork this project to bootstrap your next presentation!

== How To Use

. Remember to install Node.js and npm, and then `npm install` to setup all dependencies.
. The file `slides.adoc` contains a textual description of the slides.
. Configure the title and author at the top of the document.
. Separate slides with `==` titles.
** Please refer to the `slides.adoc` file provided for examples like bulleted lists, images, videos, source code, and Asciinema movies.
. The `Makefile` knows how to make the HTML or the PDF file; just type `make slides.html` or `make slides.pdf` while you are working.

NOTE: The speaker notes can be seen by hitting the `S` key in your keyboard while the slides are showing on the browser.

== Browser Compatibility

This template provides the same visual experience in any modern browser. It has been tested with:

* All Platforms:
** Chrome
** Opera
** Firefox
* Microsoft Windows:
** Edge
* Apple macOS:
** Safari

All browsers display the same visuals, including the default VSHN font, movies and other features.

TIP: Use a reverse proxy like https://ngrok.com/[ngrok] to share your slides live with your audience!

== Requisites

This presentation is built from Asciidoc sources using the https://asciidoctor.org/docs/asciidoctor-revealjs/[Asciidoctor Reveal.js] integration.

It requires Node.js (version 10 or higher) and npm (version 6 or higher). It is recommended to use the https://github.com/nvm-sh/nvm[Node Version Manager] to install them.

== Build

Use the command `make` to build the presentation file. The new file `slides.html` is your presentation, to be open with any standards-compliant browser. This task also creates a `slides.pdf` file, ready to be shared.

== Docker

Run `docker-compose up --build` and open your browser at http://localhost:8080/ to see the presentation. The PDF slides are located at the URL http://localhost:8080/slides.pdf ready to be downloaded.

TIP: Leaving out the `d` flag enables you to easily start/stop the presentation with a rebuild in between, for easier development.
