= Reveal.js Presentation Template

Fork this project to bootstrap your next presentation!

== Bootstrap

[source,bash]
----
$ git clone git@git.vshn.net:education/revealjs-template.git
$ revealjs-template/bootstrap.sh [YOUR-PRESENTATION-NAME-HERE]
----

The script will generate a new folder with the name `[YOUR-PRESENTATION-NAME-HERE]` ready to be built with the `make` command.

== Structure of a Presentation Project

. The file `slides.adoc` contains a textual description of the slides.
. The folder 'assets' contains all the resources used in the presentation (images, code snippets, etc)
. Configure the title and author at the top of the document.
. Separate slides with `==` titles.
** Please refer to the `slides.adoc` file provided for examples like bulleted lists, images, videos, source code, and Asciinema movies.
. The `Makefile` knows how to make the HTML or the PDF file; just type `make slides.html` or `make slides.pdf` while you are working.

NOTE: The speaker notes can be seen by hitting the `S` key in your keyboard while the slides are showing on the browser.

== Browser Compatibility

This template provides the same visual experience in any modern browser. It has been tested with:

* All Platforms:
** Chrome
** Opera
** Firefox
* Microsoft Windows:
** Edge
* Apple macOS:
** Safari

All browsers display the same visuals, including the default VSHN font, movies and other features.

TIP: Use a reverse proxy like https://ngrok.com/[ngrok] to share your slides live with your audience!

== Requisites

The requirements for this project are:

* `git`
* `docker`
* `make`

== Build

Use the command `make` to build the presentation file. The new file `slides.html` is your presentation, to be open with any standards-compliant browser. This task also creates a `slides.pdf` file, ready to be shared.

NOTE: For a PDF version, visit "Jobs" in the GitLab UI, click "Download Artifacts" on the right for the export/pdf row.

== Docker

Run `docker-compose up --build` and open your browser at http://localhost:8080/ to see the presentation. The PDF slides are located at the URL http://localhost:8080/slides.pdf ready to be downloaded.

TIP: Leaving out the `d` flag enables you to easily start/stop the presentation with a rebuild in between, for easier development.

